# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ruby_route.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ruby_route.proto", :syntax => :proto3) do
    add_message "rubyroute.PersonRequest" do
      optional :name, :string, 1
    end
    add_message "rubyroute.PersonResponse" do
      optional :email, :string, 1
    end
  end
end

module Rubyroute
  PersonRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rubyroute.PersonRequest").msgclass
  PersonResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rubyroute.PersonResponse").msgclass
end
